### ISSUE TITLE
"..." on Pagination isnt working.

### ISSUE THREAD

**Issue by leobre22** [wpexplorer/wpex-pronto#1]
The .... on the Pagination isnt working.

**Comment by wpexplorer** [comment]
It's not intended to do anything, it just shows that there are more pages in between the small and larger numbers which is part of the function used in the theme. See here: https://developer.wordpress.org/reference/functions/paginate_links/

I could update the theme to include a filter so the function parameters can be modified via a child theme though if wanted.
