### ISSUE TITLE
The Font Size of the Menu is very small

### ISSUE THREAD

**Issue by leobre22** [wpexplorer/wpex-pronto#2]
The Font Size should be bigger then it is now.

**Comment by wpexplorer** [comment]
You can use some CSS to apply a different font-size to the sidebar. Example:

<pre>
.sidebar-container { font-size: 14px !important; }
</pre>

Simply change the 14 value to the pixels you prefer.

You can add Custom CSS in WordPress under Appearance > Customize > Additional CSS
